spring:
  application:
    name: scdemo-client
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    alibaba:
      seata:
        tx-service-group: test_tx_group
  datasource:
    username: root
    password: "#2Jhdu388"
    url: jdbc:mysql://192.168.31.36:3306/scdemo?characterEncoding=UTF-8&&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.31.36
    port: 6379


server:
  port: 9002
  servlet:
    context-path: /
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka

feign:
  hystrix:
    enabled: true