spring:
  application:
    name: scdemo-client
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 9002
  servlet:
    context-path: /
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka

feign:
  hystrix:
    enabled: true